### ISSUE TITLE
Import errors for ESM

### ISSUE THREAD

**Issue by acolytec3** [paulmillr/trusted-setups#1]
I'm having trouble importing the ESM export for this module in `ethereumjs` code when I run our client in nodeJS (not with ts-node/tsx).

If I import using:
```js
import trustedSetup from `@paulmillr/trusted-setups`
...
const kzg = new KZG(trustedSetup.trustedSetup)
```

I get this error
![image](https://github.com/user-attachments/assets/f7d3b570-f5e8-4a1b-a04c-a85737411e5e)

If I import as a named export: 
```js
import { trustedSetup } from `@paulmillr/trusted-setups`
```
I get this error:
![image](https://github.com/user-attachments/assets/0fdbfe6c-ff2c-46d6-a9e8-12392cafa325)

I'm not sure why node isn't interpreting the exports map correctly in `package.json` but I've tried every trick I know.  

It works fine when we use `tsx` so not sure why node is having trouble here.  

You can see what I mean in [this branch](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3674)

If you look at our CI, the client [`cli` tests](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/10961221055/job/30437727127) (which use `tsx` to invoke the client) have no issues but our [Docker build job fails](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/10961221055/job/30437728068#step:5:388) since it uses `node ./dist/esm/bin/cli.js` to run our client in native javascipt.

Any suggestions?

**Comment by paulmillr** [comment]
https://github.com/paulmillr/trusted-setups/releases/tag/0.1.1

**Comment by acolytec3** [comment]
Thanks for the quick fix here. Looks like maybe you didn't include the types in the new release?  I'm not seeing them when I upgrade to 0.1.1 from npm.

**Comment by paulmillr** [comment]
https://github.com/paulmillr/trusted-setups/releases/tag/0.1.2
